/* Generated by Babel */
'use strict';

module.exports = (function () {

    var goalSet = document.getElementById('goalSet');
    var goalInput = document.getElementById('goalValue');
    var goal = document.getElementById('goal');
    var goalValue = [];

    goalSet.addEventListener('click', setGoal);

    function setGoal() {
        goal.innerHTML = goalInput.value;
        goalValue.push(goalInput.value);
        console.log(goalValue);
        var goalValueL = goalValue.length;
        return Number(goalValue[goalValueL - 1]);
    }

    return {
        setGoal: setGoal
    };
})();