/* Generated by Babel */
//Toggling the letters
'use strict';

function letterToggle(event) {
    var target = event.target;
    target.innerHTML = numberGenerator();
}

var span = document.getElementsByTagName('span');
for (var i = 0; i < span.length; i++) {
    span[i].addEventListener('mouseover', letterToggle);
}

//Generating binary numbers
function numberGenerator() {
    return Math.round(Math.random());
}